import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const OUT_DIR = join(ROOT, 'src/shared')
const OUT = join(OUT_DIR, 'version.ts')

const { version } = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'))

const out = `// AUTOGENERATED by scripts/generate-version.mjs — do not edit.
export const VERSION = '${version}'
`

mkdirSync(OUT_DIR, { recursive: true })
writeFileSync(OUT, out)
console.log(`Generated ${OUT} (${version})`)
